{{- if .Values.route.create -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "java-client-ol.fullname" . }}
  app: {{ include "java-client-ol.fullname" . }}
spec:
  port:
    targetPort: 9080-tcp
  to:
    kind: Service
    name: {{ include "java-client-ol.fullname" . }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{- end }}